### ISSUE TITLE
"DISABLE_LOCAL_LOG_STORAGE true" unhandled exception occurred

### ISSUE THREAD

**Issue by exequielrafaela** [stamparm/maltrail#104]
Dear stamparm,

All works fine following the below presented instrucctions from the documentation for a distributed mailtrail implementation (eg: NODE-A(Server) + NODE-B(Sensor) + NODE-C(Sensor)) hosted in 3 LXD/LXC Conteiners insisde a VBox provisioned with Vagrant + Fabric:

However when following the instructions below: 
#Option UDP_ADDRESS contains the server's log collecting listening address
#(Note: use 0.0.0.0 to listen on all interfaces), while option UDP_PORT contains
#listening port value. If turned on, when used in combination with option LOG_SERVER,
#it can be used for distinct (multiple) Sensor <-> Server architecture.

When setting "DISABLE_LOCAL_LOG_STORAGE true" in the Sensors maltrail.conf together with LOG_SERVER 10.31.54.125:8337 I receive an unhandled exception:

[ebarrirero@lxd-centos-03 maltrail]$ sudo python sensor.py  &
Maltrail (sensor) #v0.10.133
[i] using configuration file '/home/ebarrirero/maltrail/maltrail.conf'
[!] unhandled exception occurred ('any() takes exactly one argument (2 given)')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "sensor.py", line 978, in <module>
    main()
  File "sensor.py", line 951, in main
    read_config(options.config_file)
  File "/home/ebarrirero/maltrail/core/settings.py", line 305, in read_config
    if config.DISABLE_LOCAL_LOG_STORAGE and not any (config.LOG_SERVER, config.SYSLOG_SERVER):
TypeError: any() takes exactly one argument (2 given)
'

====================================

I attach server and sensor maltrail.conf below which actually has the LOG_SERVER configured, when DISABLE_LOCAL_LOG_STORAGE false all works perfect (Yet, I don't want to have the logs duplicated locally in each sensor and the server).

### #Listen address of (reporting) HTTP server
HTTP_ADDRESS 0.0.0.0

### # Listen port of (reporting) HTTP server
HTTP_PORT 8338

### # Use SSL/TLS
USE_SSL false

### #          filter_netmask(s) is/are used to filter results
USERS
###    #admin:9ab3cd9d67bf49d01f6a2e33d0bd9bc804ddbe6ce1ff5d219c42624851db5dbc:0:0.0.0.0/0 # changeme!
    ebarrirero:03b9bb6e1d6bd815370da1fac4926933a037ec11c975bc7fd61476c4549143d0:0:0.0.0.0/0
    
### # Listen address of (log collecting) UDP server
UDP_ADDRESS 0.0.0.0

### # Listen port of (log collecting) UDP server
UDP_PORT 8337

### # Should server do the trail updates too (to support UPDATE_SERVER)
USE_SERVER_UPDATE_TRAILS true

### # Show debug messages (in console output)
SHOW_DEBUG false

### # Directory used for log storage
LOG_DIR $SYSTEM_LOG_DIR/maltrail

### #PROXY_ADDRESS http://192.168.5.101:8118

====================================

### # Number of processes
PROCESS_COUNT $CPU_CORES

### # Disable setting of CPU affinity (with schedtool) on Linux machines (e.g. because of load issues with other processes)
DISABLE_CPU_AFFINITY false

### # Use feeds (too) in trail updates
USE_FEED_UPDATES true

### # Update trails after every given period (seconds)
UPDATE_PERIOD 86400

### # Location of directory with custom trails (*.txt) files
CUSTOM_TRAILS_DIR ./trails/custom

### # (Max.) size of multiprocessing network capture ring buffer (in bytes or percentage of total physical memory) used by sensor (e.g. 512MB)
CAPTURE_BUFFER 10%

### # Interface used for monitoring (e.g. eth0, eth1)
MONITOR_INTERFACE any

### #CAPTURE_FILTER ip or ip6
CAPTURE_FILTER udp or icmp or (tcp and (tcp[tcpflags] == tcp-syn or port 80 or port 1080 or port 3128 or port 8000 or port 8080 or port 8118))

### # Sensor name to appear in produced logs
SENSOR_NAME $HOSTNAME

### # Remote address to send log entries
LOG_SERVER 10.31.54.125:8337

### # Remote address to send syslog entries
#SYSLOG_SERVER 10.31.54.125:514

### # Use only (!) in cases when LOG_SERVER should be used for log storage
DISABLE_LOCAL_LOG_STORAGE true

### # Remote address for pulling (latest) trail definitions (e.g. http://192.168.2.107:8338/trails)
UPDATE_SERVER http://10.31.54.125:8338/trails

### # Use heuristic methods
USE_HEURISTICS true

### # Capture HTTP requests with missing Host header (introducing potential false positives)
CHECK_MISSING_HOST false

### # Check values in Host header (along with standard non-HTTP checks) for malicious DNS trails (introducing greater number of events)
CHECK_HOST_DOMAINS false

### # Show debug messages (in console output)
SHOW_DEBUG false

### # Directory used for log storage
LOG_DIR $SYSTEM_LOG_DIR/maltrail

### #PROXY_ADDRESS http://192.168.5.101:8118

[maltrail_conf.tar.gz](https://github.com/stamparm/maltrail/files/462235/maltrail_conf.tar.gz)

**Comment by exequielrafaela** [comment]
Many thanks! :dart:

**Comment by exequielrafaela** [comment]
I'll test it ASAP and let you know! :dash:

**Comment by exequielrafaela** [comment]
Works like a charm! Great job :D
