### ISSUE TITLE
TypeError: cannot pickle 'mmap.mmap' object '

### ISSUE THREAD

**Issue by nmweizi** [stamparm/maltrail#11823]
- git clone
- python3.8 sensor.py

```
[i] creating 7 more processes (out of total 8)
[!] unhandled exception occurred ('cannot pickle 'mmap.mmap' object')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "sensor.py", line 1224, in <module>
    main()
  File "sensor.py", line 1211, in main
    init()
  File "sensor.py", line 975, in init
    _init_multiprocessing()
  File "sensor.py", line 1026, in _init_multiprocessing
    process.start()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'mmap.mmap' object
'
---
[i] finished

**Comment by stamparm** [comment]
Tried on Ubuntu 20.04 with both Python 3.8 and 3.9. Can't reproduce

**Comment by nmweizi** [comment]
> Tried on Ubuntu 20.04 with both Python 3.8.5 and 3.9.0. Unable to reproduce

Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Comment by nmweizi** [comment]
complement
python2.7 is fine

**Comment by nmweizi** [comment]
- debian python 3.8.5 is fine
- darwin python 3.8.5 error
- darwin python 3.9.0 error

#### maybe darwin python bug?

**Comment by stamparm** [comment]
I have a "hunch" what's going on. `multiprocessing` library is on each system implemented differently. In typical Linux installation, `os.fork` is used as a base, while I suspect that in `Darwin` they switched to something else in the mean-time.

p.s.: `os.fork` makes a seamless copy of variables between two processes, thus the lack of that error in Linux environment
p.p.s. yesterday I played a bit with some other options to deal with this, but it does not seem trivial to do it. will need more (free) time to properly research it an patch it

**Comment by stamparm** [comment]
@nmweizi done a dummy patch for your case. It just does a failback to single-process mode, but it should work without any problems

**Comment by nmweizi** [comment]
> @nmweizi done a dummy patch for your case. It just does a failback to single-process mode, but it should work without any problems

patch is fine
