### ISSUE TITLE
pcapy not detected

### ISSUE THREAD

**Issue by swetoast** [stamparm/maltrail#134]
Installed pcapy at this path

```
Installed /volume1/.@plugins/AppCentral/python/lib/python2.7/site-packages/pcapy-0.11.1-py2.7-linux-armv7l.egg
Processing dependencies for pcapy==0.11.1
Finished processing dependencies for pcapy==0.11.1
```
when i run the server it runs just fine but the sensor does not detect pcapy even thou its installed
```
 # python sensor.py 
Maltrail (server) #v0.10.260

[i] using configuration file '/volume1/.@user/maltrail/maltrail.conf'
[i] starting HTTP server at 'http://0.0.0.0:8338/'
[o] running...
[x] stopping (Ctrl-C pressed)
[i] finished
:~/maltrail # python sensor.py 
[!] please install 'Pcapy'
````

**Comment by stamparm** [comment]
Please do the following:

```
sudo su
python -c 'import pcapy'
```

to check the installation

**Comment by swetoast** [comment]
```
# python -c 'import pcapy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-armv7l/egg/pcapy.py", line 7, in <module>
  File "build/bdist.linux-armv7l/egg/pcapy.py", line 6, in __bootstrap__
ImportError: libpcap.so.0.8: cannot open shared object file: No such file or directory
```
it didnt install properly, guess ill have to go back to the drawing board and try and install it again, sorry for wasting your time

**Comment by swetoast** [comment]
Whole different beast trying to install this with entware and asuswrt-merlin firmware on a router :)
so i might comeback with questions on more issues further down the line since this project would be awesome to have built into the router.
