### ISSUE TITLE
module' object has no attribute 'TLSv1_2_METHOD

### ISSUE THREAD

**Issue by mpricu** [stamparm/maltrail#16250]
Hi,

I tried to run Server maltrail on Centos 7.9 . First I received the message to install pyopenssl package, so I run "yum install pyOpenSSL" and the pyOpenSSL-0.13.1-4.el7.x86_64 package was installed.
When I tried to run "python server.py" I received te following message:

[i] using configuration file '/root/maltrail/maltrail.conf'
[!] unhandled exception occurred (''module' object has no attribute 'TLSv1_2_METHOD'')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "server.py", line 124, in <module>
    main()
  File "server.py", line 116, in main
    start_httpd(address=config.HTTP_ADDRESS, port=config.HTTP_PORT, pem=config.SSL_PEM if config.USE_SSL else None, join=True)
  File "/root/maltrail/core/httpd.py", line 722, in start_httpd
    server = SSLThreadingServer(_address, pem, SSLReqHandler)
  File "/root/maltrail/core/httpd.py", line 97, in __init__
    ctx = OpenSSL.SSL.Context(OpenSSL.SSL.TLSv1_2_METHOD)
AttributeError: 'module' object has no attribute 'TLSv1_2_METHOD'

The python version is 2.7.5 

Thank you for your help.

**Comment by stamparm** [comment]
Please retrieve the latest revision and retry. Hopefully it should be fixed now

**Comment by mpricu** [comment]
Hi Miroslav,

The Server started now, but when I connected to it I received the following error in Firefox (version 78.10.0esr):

"Secure Connection Failed

An error occurred during a connection to 0.0.0.0:8338. Peer using unsupported version of security protocol.

Error code: SSL_ERROR_UNSUPPORTED_VERSION

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

This website might not support the TLS 1.2 protocol, which is the minimum version supported by Firefox. Enabling TLS 1.0 and TLS 1.1 might allow this connection to succeed.

TLS 1.0 and TLS 1.1 will be permanently disabled in a future release."

There is a button to enable TLS 1.0 and TLS 1.1,  which I did and I could connect finally to the Server.

I think for now it is OK, but maybe in the future will be good to enable connection with TLS 1.2, since TLS 1.0 and TLS 1.1 were deprecated in 2020.

With latest Google Chrome (version 90.0.4430.93) I also could connect even if I saw the following error:

"ERROR:ssl_client_socket_impl.cc(947)] handshake failed; returned -1, SSL error code 1, net_error -202"

Thank you very much for your help.

Mircea

**Comment by mpricu** [comment]
I checked again and I saw the Google Chrome show "This page is not secure (broken HTTPS)" message because the TLS version is 1.0 .
I think it's better to enable TLS version 1.2 or even version 1.3 in the code to secure the connection to the Maltrail Server.

Thank you very much for your help.

**Comment by stamparm** [comment]
p.s. checked with Python3.8.6. Getting TLS 1.3

**Comment by mpricu** [comment]
Hi,

Yes, on Ubuntu 20.04 the openssl version is 1.1.1f with Python 3.8.5 and the TLS is 1.3. 

But on Centos 7 we have Python 2.7.5 and openssl version 1.0.2k. So I installed openssl version 1.1.1f and I still have TLS version 1.0 for the Maltrail server. 

Thank you for your help.

**Comment by mpricu** [comment]
Hi,

I tried the other way around , so I installed Python version 3.6.8 and set it as default python version. After that the Maltrail server was using TLS 1.2 with the openssl version 1.0.2k, so the Python version is important, not the openssl version.

Thank you for your help.
