### ISSUE TITLE
maltrails 0.50 fails to start throws error

### ISSUE THREAD

**Issue by jafo65** [stamparm/maltrail#19123]
[*] starting @ 13:22:59 /2022-10-18/

[i] using configuration file '/opt/maltrail/maltrail.conf'
[i] using '/cache/maltrail' for log storage
[i] using '/root/.maltrail/trails.csv' for trail storage (last modification: 'Tue, 18 Oct 2022 05:22:08 GMT')
[i] retrieving trails from provided 'UPDATE_SERVER' server...
[i] loading trails...
[i] 574,406 trails loaded
[!] unhandled exception occurred ('eth1: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Device or resource busy')
[x] please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "/opt/maltrail/sensor.py", line 1290, in <module>
    main()
  File "/opt/maltrail/sensor.py", line 1277, in main
    init()
  File "/opt/maltrail/sensor.py", line 982, in init
    if interface.lower() != "any" and re.sub(r"(?i)\Anetmap:", "", interface) not in pcapy.findalldevs():
pcapy.PcapError: eth1: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Device or resource busy

no eth1 enabled...
just
eth0
wg0 
wlan0

eth0 is front facing to Internet

running on dietpi on ARM bullseye

**Comment by MikhailKasimov** [comment]
Hello!

Please, show ```ifconfig``` output.

**Comment by stamparm** [comment]
@jafo65 please try to pull the latest revision (pushed this moment) and retry

**Comment by MikhailKasimov** [comment]
@jafo65 Hello! Any news from your side? Is the problem reproducable with patch? Thank you!

**Comment by stamparm** [comment]
That's 0.50 - the sensor and the loader have been rewritten twice since. Closing as stale; if something similar shows up on 3.1.x please open a fresh issue with the startup output.
