### ISSUE TITLE
BUG: OverflowError: in Voipbl.py

### ISSUE THREAD

**Issue by darkwarriors** [stamparm/maltrail#3]
here the exception:

```
[i] updating trails...
 [o] 'https://feodotracker.abuse.ch/blocklist/?download=domainblocklist'
[!] something went wrong during remote data retrieval ('https://feodotracker.abuse.ch/blocklist/?download=domainblocklist')
 [o] 'https://www.badips.com/get/list/any/2?age=30d'
 [o] 'https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ri_web_proxies_30d.ipset'
 [o] 'https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/proxylists_30d.ipset'
 [o] 'http://www.botscout.com/last_caught_cache.htm'
 [o] 'http://vxvault.siri-urz.net/URL_List.php'
 [o] 'http://malwaredomains.lehigh.edu/files/domains.txt'
 [o] 'https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/socks_proxy_30d.ipset'
 [o] 'https://zeustracker.abuse.ch/blocklist.php?download=badips'
 [o] 'https://openphish.com/feed.txt'
 [o] 'https://myip.ms/files/blacklist/htaccess/latest_blacklist.txt'
 [o] 'https://www.maxmind.com/en/proxy-detection-sample-list'
 [o] 'https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist'
 [o] 'http://malwareurls.joxeankoret.com/normal.txt'
 [o] 'http://talosintel.com/feeds/ip-filter.blf'
 [o] 'https://check.torproject.org/cgi-bin/TorBulkExitList.py?ip=1.1.1.1'
 [o] 'https://rules.emergingthreats.net/open/suricata/rules/emerging-dns.rules'
 [o] 'http://www.nothink.org/blacklist/blacklist_malware_irc.txt'
 [o] 'http://danger.rulez.sk/projects/bruteforceblocker/blist.php'
 [o] 'http://malwared.malwaremustdie.org/rss.php'
 [o] 'http://www.voipbl.org/update/'
[!] Unhandled exception occurred ('Python int too large to convert to C long')
[x] Please report the following details at 'https://github.com/stamparm/maltrail/issues':
---
'Traceback (most recent call last):
  File "sensor.py", line 389, in <module>
    main()
  File "sensor.py", line 382, in main
    init()
  File "sensor.py", line 287, in init
    update_timer()
  File "sensor.py", line 275, in update_timer
    _ = update(server=config.UPDATE_SERVER)
  File "/opt/maltrail/maltrail/core/update.py", line 82, in update
    results = function()
  File "/opt/maltrail/maltrail/trails/feeds/voipbl.py", line 29, in fetch
    for address in xrange(start_int, end_int + 1):
OverflowError: Python int too large to convert to C long
'
---
```

Debian 6
Python 2.7.3

Thanks for your amazing work!!

**Comment by stamparm** [comment]
@darkwarriors wihoooo. somebody else uses it other than me and my work colleagues :D. I am glad that you like it.

**Comment by darkwarriors** [comment]
thanks for the fix! iam testing it in my honeynet sensor, it is very cool! i have some doubts about heuristic detection because i am not able to understand how to trigger that behavior, i tried alot of uri but without success, i will look inside the python code how it works ( sensor.py right ? )

**Comment by stamparm** [comment]
@darkwarriors any kind of web scanner (e.g. sqlmap) should trigger it. Also, simple `?id=<script>alert('XSS')</script>` should trigger it, no matter if the request is toward your site or from the internal network to the outside
